export function generateReportHtml(url: string, result: any): string {
  const { ruleChecks, aiAnalysis } = result;
  const score = aiAnalysis?.gdprScore || 0;
  const scoreColor = score >= 70 ? '#22c55e' : score >= 40 ? '#f59e0b' : '#ef4444';
  const riskLabel = aiAnalysis?.riskLevel || 'unknown';

  const checksHtml = ruleChecks.map((check: any) => `
    <div style="padding:12px;margin:8px 0;border-radius:8px;background:#f5f5f5;border-left:4px solid ${check.passed ? '#22c55e' : '#ef4444'};">
      <strong>${escapeHtml(check.name)}</strong> — ${check.passed ? 'PASS' : 'FAIL'}
      <p style="margin:4px 0 0 0;color:#666;">${escapeHtml(check.detail || '')}</p>
      ${check.recommendation ? `<p style="margin:4px 0 0 0;color:#888;font-style:italic;">Fix: ${escapeHtml(check.recommendation)}</p>` : ''}
    </div>
  `).join('');

  const issuesHtml = aiAnalysis?.issues?.length
    ? aiAnalysis.issues.map((issue: any) => `
        <div style="padding:12px;margin:8px 0;border-radius:8px;background:#fef2f2;border-left:4px solid ${issue.severity === 'critical' ? '#ef4444' : issue.severity === 'warning' ? '#f59e0b' : '#3b82f6'};">
          <strong>[${issue.severity?.toUpperCase() || 'INFO'}] ${escapeHtml(issue.title || '')}</strong>
          <p style="margin:4px 0 0 0;color:#666;">${escapeHtml(issue.description || '')}</p>
          ${issue.fix ? `<p style="margin:4px 0 0 0;"><strong>Fix:</strong> ${escapeHtml(issue.fix)}</p>` : ''}
        </div>
      `).join('')
    : '';

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>GDPR Compliance Report — ${escapeHtml(url)}</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; color: #1a1a2e; background: #fff; }
    .header { text-align: center; margin-bottom: 40px; }
    .logo { font-size: 28px; font-weight: bold; color: #4f8ef7; }
    .url { color: #666; margin-top: 4px; }
    .score-section { text-align: center; margin-bottom: 40px; }
    .score { font-size: 96px; font-weight: bold; color: ${scoreColor}; line-height: 1; }
    .score-label { color: #666; font-size: 14px; margin-top: 4px; }
    .risk-badge { display: inline-block; background: ${scoreColor}; color: #fff; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; margin-top: 8px; text-transform: uppercase; }
    .summary { background: #f9f9f9; padding: 20px; border-radius: 12px; margin-bottom: 30px; line-height: 1.6; }
    .section { margin-bottom: 30px; }
    .section h2 { color: #0f0f1a; border-bottom: 2px solid #4f8ef7; padding-bottom: 8px; margin-bottom: 16px; }
    .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #eee; color: #999; font-size: 12px; text-align: center; }
    a { color: #4f8ef7; }
    .back { display: inline-block; margin-bottom: 20px; color: #666; text-decoration: none; font-size: 14px; }
    .back:hover { color: #4f8ef7; }
  </style>
</head>
<body>
  <a href="/dashboard" class="back">← Back to Dashboard</a>
  <div class="header">
    <div class="logo">ComplyScan</div>
    <h1 style="font-size:22px;margin:12px 0 4px;">GDPR Compliance Report</h1>
    <p class="url"><a href="${escapeHtml(url)}" target="_blank">${escapeHtml(url)}</a></p>
  </div>

  <div class="score-section">
    <div class="score">${score}</div>
    <div class="score-label">out of 100 — GDPR Compliance Score</div>
    <div><span class="risk-badge">${riskLabel.toUpperCase()} RISK</span></div>
  </div>

  ${aiAnalysis?.summary ? `<div class="summary">${aiAnalysis.summary}</div>` : ''}

  <div class="section">
    <h2>Automated Checks</h2>
    ${checksHtml}
  </div>

  ${issuesHtml ? `<div class="section">
    <h2>AI-Detected Issues (${aiAnalysis.issues.length})</h2>
    ${issuesHtml}
  </div>` : ''}

  <div class="footer">
    <p>Generated by ComplyScan — GDPR compliance made effortless</p>
    <p>Report generated: ${new Date().toLocaleDateString('en-GB', { timeZone: 'Europe/Zurich' })}</p>
  </div>
</body>
</html>`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
