import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy | ComplyScan",
  description:
    "Privacy Policy for ComplyScan — learn how we collect, use, and protect your data when you use our GDPR compliance scanning service.",
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-midnight text-white">
      <header className="border-b border-white/10">
        <div className="max-w-3xl mx-auto px-4 py-6 flex items-center justify-between">
          <Link
            href="/"
            className="text-xl font-bold"
            style={{ fontFamily: "var(--font-space-grotesk)" }}
          >
            ComplyScan
          </Link>
          <Link
            href="/"
            className="text-sm text-white/60 hover:text-white transition-colors"
          >
            Back to home
          </Link>
        </div>
      </header>

      <article className="max-w-3xl mx-auto px-4 py-12">
        <h1
          className="text-3xl md:text-4xl font-bold mb-8"
          style={{ fontFamily: "var(--font-space-grotesk)" }}
        >
          Privacy Policy
        </h1>
        <p className="text-white/50 text-sm mb-8">Last updated: March 30, 2026</p>

        <div className="prose prose-invert prose-lg max-w-none space-y-8">
          <section>
            <h2
              className="text-xl font-bold mb-3"
              style={{ fontFamily: "var(--font-space-grotesk)" }}
            >
              1. Who We Are
            </h2>
            <p>
              ComplyScan (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) is an automated GDPR compliance scanning service.
              We are committed to protecting the privacy and personal data of our users
              and the visitors to websites our users scan.
            </p>
            <p>
              Contact us at:{" "}
              <a
                href="mailto:compliance@complyscan.com"
                className="text-accent-blue hover:underline"
              >
                compliance@complyscan.com
              </a>
            </p>
          </section>

          <section>
            <h2
              className="text-xl font-bold mb-3"
              style={{ fontFamily: "var(--font-space-grotesk)" }}
            >
              2. Data We Collect
            </h2>
            <p>When you use ComplyScan, we collect the following data:</p>

            <h3 className="font-semibold mt-4 mb-2">Data you provide directly:</h3>
            <ul>
              <li><strong>Email address</strong> — required to receive scan reports</li>
              <li><strong>Billing information</strong> — processed by Stripe; we do not store credit card numbers</li>
            </ul>

            <h3 className="font-semibold mt-4 mb-2">Data collected during scanning:</h3>
            <ul>
              <li><strong>URL scanned</strong> — the website address you submit for analysis</li>
              <li><strong>Scan results</strong> — the compliance findings generated by our analysis engine</li>
              <li><strong>Publicly accessible page content</strong> — the system crawls and analyses publicly accessible pages of the submitted URL (no private areas, login-protected pages, or behind-authentication content)</li>
              <li><strong>IP address and user agent</strong> — collected during the scan for security and rate-limiting purposes</li>
            </ul>

            <h3 className="font-semibold mt-4 mb-2">Automatically collected:</h3>
            <ul>
              <li><strong>Session and usage data</strong> — pages visited, features used, timestamps, and general interaction patterns</li>
              <li><strong>Cookies</strong> — strictly necessary session cookies to maintain your authenticated session; optional analytics cookies if you consent to them</li>
            </ul>
          </section>

          <section>
            <h2
              className="text-xl font-bold mb-3"
              style={{ fontFamily: "var(--font-space-grotesk)" }}
            >
              3. How We Use Your Data
            </h2>
            <p>We use your data for the following purposes:</p>
            <ul>
              <li><strong>Deliver scan reports</strong> — to email you the compliance findings from your scan</li>
              <li><strong>Process payments</strong> — via Stripe; we never store payment card details</li>
              <li><strong>Service improvement</strong> — to understand how users interact with ComplyScan and improve the service</li>
              <li><strong>Security and fraud prevention</strong> — to detect and prevent abuse, unauthorized access, and fraudulent transactions</li>
              <li><strong>Legal compliance</strong> — to comply with applicable laws, respond to legal requests, and meet our regulatory obligations</li>
            </ul>
            <p>
              We do <strong>not</strong> sell, rent, or trade your personal data to third parties
              for marketing purposes.
            </p>
          </section>

          <section>
            <h2
              className="text-xl font-bold mb-3"
              style={{ fontFamily: "var(--font-space-grotesk)" }}
            >
              4. Data Retention
            </h2>
            <p>We retain your data for different periods depending on the type and your subscription:</p>
            <ul>
              <li><strong>Free or one-time scans:</strong> Scan results (URL, findings, page content snapshots) are retained for <strong>30 days</strong> after the scan date, then automatically deleted.</li>
              <li><strong>Monthly subscribers:</strong> Scan history is retained for <strong>12 months</strong> from the date of each scan, then automatically deleted.</li>
              <li><strong>Email address:</strong> Retained for the duration of your active subscription plus 90 days after cancellation, for record-keeping purposes.</li>
              <li><strong>Billing records:</strong> Retained for a minimum of 7 years to comply with financial and tax record-keeping obligations.</li>
            </ul>
            <p>
              Upon request, we will delete or anonymize your personal data sooner, except
              where retention is required by law.
            </p>
          </section>

          <section>
            <h2
              className="text-xl font-bold mb-3"
              style={{ fontFamily: "var(--font-space-grotesk)" }}
            >
              5. Data Sharing
            </h2>
            <p>
              ComplyScan does not share your personal data with third parties except in
              the following limited circumstances:
            </p>
            <ul>
              <li>
                <strong>Stripe</strong> — for payment processing. Stripe's privacy policy
                governs their data handling:{" "}
                <a
                  href="https://stripe.com/privacy"
                  className="text-accent-blue hover:underline"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  stripe.com/privacy
                </a>
              </li>
              <li>
                <strong>Resend</strong> — for transactional email delivery (sending you scan
                reports). Resend's privacy policy is available at:{" "}
                <a
                  href="https://resend.com/privacy"
                  className="text-accent-blue hover:underline"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  resend.com/privacy
                </a>
              </li>
              <li>
                <strong>Law enforcement and regulators</strong> — when required by law,
                court order, or to protect our legal rights
              </li>
              <li>
                <strong>Service providers</strong> — hosting and infrastructure providers
                who are contractually bound to protect your data and use it only for
                the services they provide to us
              </li>
            </ul>
          </section>

          <section>
            <h2
              className="text-xl font-bold mb-3"
              style={{ fontFamily: "var(--font-space-grotesk)" }}
            >
              6. Data Processed on Behalf of Our Users
            </h2>
            <p>
              When you scan a website using ComplyScan, our system processes publicly
              accessible web pages of that website. This includes crawling and
              temporarily storing page content to perform compliance analysis. This
              data (the scanned page content and resulting findings) belongs to you
              the user and is subject to your control under our data retention policy above.
            </p>
            <p>
              We act as a <strong>Data Processor</strong> with respect to scanned website
              data. The website owner (you, the user of ComplyScan) act as the{" "}
              <strong>Data Controller</strong> with respect to that data. You are
              responsible for ensuring you have the necessary rights and legal basis
              to submit a website for compliance scanning.
            </p>
          </section>

          <section>
            <h2
              className="text-xl font-bold mb-3"
              style={{ fontFamily: "var(--font-space-grotesk)" }}
            >
              7. Cookies
            </h2>
            <p>
              ComplyScan uses only strictly necessary cookies for session management.
              We do not use advertising, analytics, or tracking cookies unless you
              explicitly opt in.
            </p>
            <ul>
              <li>
                <strong>Session cookie</strong> — authenticates your account and maintains
                your logged-in session. Expires when you log out or after 24 hours of inactivity.
              </li>
              <li>
                <strong>Consent cookie</strong> — remembers your cookie preference choice.
                Expires after 12 months.
              </li>
            </ul>
          </section>

          <section>
            <h2
              className="text-xl font-bold mb-3"
              style={{ fontFamily: "var(--font-space-grotesk)" }}
            >
              8. Security
            </h2>
            <p>
              We implement appropriate technical and organizational measures to protect
              your data, including: encryption in transit (TLS), access controls and
              least-privilege principles, regular security reviews, and secure cloud
              infrastructure with SOC 2-compliant providers.
            </p>
            <p>
              No security measure is 100% foolproof. In the event of a data breach
              that affects your rights, we will notify you and the relevant supervisory
              authority within 72 hours as required by GDPR Article 33.
            </p>
          </section>

          <section>
            <h2
              className="text-xl font-bold mb-3"
              style={{ fontFamily: "var(--font-space-grotesk)" }}
            >
              9. Your GDPR Rights
            </h2>
            <p>Under GDPR, you have the following rights regarding your personal data:</p>
            <ul>
              <li>
                <strong>Right of access</strong> — request a copy of all personal data
                we hold about you
              </li>
              <li>
                <strong>Right to rectification</strong> — request correction of inaccurate
                personal data
              </li>
              <li>
                <strong>Right to erasure</strong> — request deletion of your personal data
                (&quot;right to be forgotten&quot;), subject to legal retention requirements
              </li>
              <li>
                <strong>Right to data portability</strong> — receive your data in a
                structured, machine-readable format
              </li>
              <li>
                <strong>Right to restrict processing</strong> — request that we limit
                how we use your data
              </li>
              <li>
                <strong>Right to object</strong> — object to processing based on
                legitimate interests
              </li>
              <li>
                <strong>Right to lodge a complaint</strong> — file a complaint with
                your local supervisory authority (e.g., your national Data Protection Authority)
              </li>
            </ul>
            <p>
              To exercise any of these rights, contact us at{" "}
              <a
                href="mailto:privacy@complyscan.com"
                className="text-accent-blue hover:underline"
              >
                privacy@complyscan.com
              </a>
              . We will respond within 30 days.
            </p>
          </section>

          <section>
            <h2
              className="text-xl font-bold mb-3"
              style={{ fontFamily: "var(--font-space-grotesk)" }}
            >
              10. International Data Transfers
            </h2>
            <p>
              ComplyScan processes data on servers located within the European Economic
              Area (EEA). Where we use service providers outside the EEA (e.g., Resend
              for email delivery), we ensure appropriate safeguards are in place, such
              as Standard Contractual Clauses approved by the European Commission.
            </p>
          </section>

          <section>
            <h2
              className="text-xl font-bold mb-3"
              style={{ fontFamily: "var(--font-space-grotesk)" }}
            >
              11. Children's Data
            </h2>
            <p>
              ComplyScan is not designed for or directed at children under 16. We do not
              knowingly collect personal data from children. If you become aware that
              a child has provided us with personal data, please contact us and we
              will delete it immediately.
            </p>
          </section>

          <section>
            <h2
              className="text-xl font-bold mb-3"
              style={{ fontFamily: "var(--font-space-grotesk)" }}
            >
              12. Changes to This Policy
            </h2>
            <p>
              We may update this Privacy Policy from time to time. Material changes will
              be communicated via email to active users at least 14 days before taking
              effect. The date of the most recent revision is always displayed at the
              top of this page.
            </p>
          </section>

          <section>
            <h2
              className="text-xl font-bold mb-3"
              style={{ fontFamily: "var(--font-space-grotesk)" }}
            >
              13. Contact
            </h2>
            <p>
              For any privacy-related questions, data subject requests, or concerns:
            </p>
            <p>
              <a
                href="mailto:privacy@complyscan.com"
                className="text-accent-blue hover:underline"
              >
                privacy@complyscan.com
              </a>
            </p>
            <p>
              You also have the right to lodge a complaint with your local Data Protection
              Authority. For EU member states, a list of national DPAs is available at:{" "}
              <a
                href="https://edpb.europa.eu/about-edpb/about-edpb/members_en"
                className="text-accent-blue hover:underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                edpb.europa.eu
              </a>
            </p>
          </section>
        </div>
      </article>
    </main>
  );
}
